from pathlib import Path
from typing import Any

from domain.models import NodeType, TestNode


def resolve_target_path(target_path: str) -> Path:
    """Resolves and validates target directory path with fallback for container runtime environments."""
    if target_path:
        p = Path(target_path).expanduser()
        if not p.is_absolute():
            cand = (Path.cwd() / p).resolve()
            if cand.exists() and cand.is_dir():
                return cand
            app_root = Path.cwd().resolve()
            if app_root.name == "backend" and (app_root.parent / "backend").exists():
                cand_parent = (app_root.parent / p).resolve()
                if cand_parent.exists() and cand_parent.is_dir():
                    return cand_parent
        else:
            resolved = p.resolve()
            if resolved.exists() and resolved.is_dir():
                return resolved

        # Container fallback when host path is passed as TARGET_REPO env var
        target_vol = Path("/target")
        if target_vol.exists() and target_vol.is_dir():
            return target_vol.resolve()
        raise ValueError(f"Invalid target path: {target_path}")

    # Fallback for empty target_path (default container/server target)
    target_vol = Path("/target")
    if target_vol.exists() and target_vol.is_dir():
        return target_vol.resolve()

    # Check TARGET_REPO env var if set
    import os
    env_target = os.getenv("TARGET_REPO", "")
    if env_target:
        try:
            return resolve_target_path(env_target)
        except Exception:
            pass

    app_root = Path.cwd().resolve()
    if app_root.name == "backend" and (app_root.parent / "backend").exists():
        app_root = app_root.parent

    sample_repo = app_root / "sample-target-repo"
    if sample_repo.exists() and sample_repo.is_dir():
        return sample_repo.resolve()

    if app_root.exists() and app_root.is_dir():
        return app_root

def is_safe_subpath(base_path: Path, sub_path: str) -> bool:
    """Verifies that sub_path stays strictly within base_path directory boundary to prevent path traversal.

    Args:
        base_path: Target root directory path.
        sub_path: Relative node or suite path to validate.

    Returns:
        bool: True if sub_path is within base_path boundary, False otherwise.
    """
    if not sub_path:
        return True
    try:
        file_part = sub_path.split("::")[0]
        resolved_sub = (base_path / file_part).resolve()
        return resolved_sub == base_path or base_path in resolved_sub.parents
    except (ValueError, OSError):
        return False



def build_tree_from_collectors(collectors: list[dict[str, Any]], suite_prefix: str = "") -> TestNode:
    """Transforms raw pytest collectors JSON structure into a domain TestNode tree.

    Args:
        collectors: Raw JSON collector output list generated by pytest-json-report.
        suite_prefix: Relative path prefix of the target test suite directory.

    Returns:
        TestNode: The root node of the parsed domain test tree.
    """
    suite_clean = suite_prefix.rstrip("/")
    root = TestNode(
        id=suite_clean or "root",
        name=suite_clean or "tests",
        type=NodeType.DIRECTORY,
        path=suite_clean or "tests",
        children=[],
    )

    node_map: dict[str, TestNode] = {"": root}

    node_ids: set[str] = set()
    for col in collectors:
        for res in col.get("result", []):
            if res.get("type") in ("Function", "Item", "TestCase"):
                nid = res.get("nodeid", "")
                if nid:
                    if suite_clean and not nid.startswith(suite_clean):
                        nid = f"{suite_clean}/{nid}"
                    node_ids.add(nid)

    for node_id in sorted(node_ids):
        parts = node_id.split("::")
        filepath = parts[0]
        func_or_class = parts[1:] if len(parts) > 1 else []

        rel_filepath = filepath
        if suite_clean and (filepath == suite_clean or filepath.startswith(suite_clean + "/")):
            rel_filepath = filepath[len(suite_clean):].lstrip("/")

        path_segments = [s for s in rel_filepath.split("/") if s]
        curr_key = ""

        for i, segment in enumerate(path_segments):
            parent_key = curr_key
            curr_key = f"{curr_key}/{segment}" if curr_key else segment

            if curr_key not in node_map:
                is_file = i == len(path_segments) - 1 and segment.endswith((".py", ".feature"))
                node_type = NodeType.FILE if is_file else NodeType.DIRECTORY
                node_id_val = filepath if is_file else (f"{suite_clean}/{curr_key}" if suite_clean else curr_key)
                
                node = TestNode(
                    id=node_id_val,
                    name=segment,
                    type=node_type,
                    path=filepath,
                    children=[],
                )
                node_map[curr_key] = node
                node_map[filepath] = node
                node_map[parent_key].children.append(node)

        curr_node_id = filepath
        for idx, item in enumerate(func_or_class):
            parent_node_id = curr_node_id
            curr_node_id = f"{curr_node_id}::{item}"

            if curr_node_id not in node_map:
                is_function = idx == len(func_or_class) - 1
                node_type = NodeType.FUNCTION if is_function else NodeType.CLASS
                node = TestNode(
                    id=curr_node_id,
                    name=item,
                    type=node_type,
                    path=filepath,
                    children=[],
                )
                node_map[curr_node_id] = node
                if parent_node_id in node_map:
                    node_map[parent_node_id].children.append(node)

    return root
